### ISSUE TITLE
Issues with specifications

### ISSUE THREAD

**Issue by mcraiha** [KhronosGroup/KTX-Specification#1]
Following issues/remarks apply to documentation in https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/

Issues in [An example KTX file:](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#4) section
1.  `0x0D, 0x0A, 0x1A, 0x0A. // final four bytes of Byte[12] identifier` should be` 0x0D, 0x0A, 0x1A, 0x0A, // final four bytes of Byte[12] identifier`
2. `0x6A, 0x6F, 0x6B, 0x65, // UTF8 v: 'gles2\0'` 0x6A, 0x6F, 0x6B, 0x65 means **j o k e**, not **g l e s**

Text above is copied from https://github.com/KhronosGroup/KTX-Software/issues/43 as requested,

**Comment by MarkCallow** [comment]
Fixed in the new 1.0 branch.
