### ISSUE TITLE
Consider specifying padding value

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#10]
The spec doesn't require fields used for byte-alignment (`blockPadding`, `valuePadding`, `keyValuePadding`, `sgdPadding`, and `mipPadding`) to be filled with a particular value (such as `0x00` of `0xFF`). 

This may lead to two files with the same texture having different checksums because different implementations may use different padding values.

**Comment by MarkCallow** [comment]
Good point. Please submit a PR.
