### ISSUE TITLE
Clarify uncompressedByteLength for BasisU compressed images

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Specification#111]
It's unclear from the specification what value `uncompressedByteLength` should contain when Basis supercompression is used.

I suspect that the answer is "0", since that's what toktx does, and it's not clear what other value we could store there, but this should be clarified in the spec because at the moment it seems like the spec suggests to put a non-0 value in.

**Comment by MarkCallow** [comment]
It should be 0. For other supercompression schemes it should be the pre-deflation size. Thanks for pointing out the need to clarify.

**Comment by MarkCallow** [comment]
PR #114 had to be aborted so this was actually closed by PR #115.
