### ISSUE TITLE
Simplify padding specification?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Specification#112]
Right now, padding for KVP data and padding for mip data is specified to not occur on the last element.

While this is sufficient, this makes the padding handling a touch more complicated. libktx doesn't do this properly right now, which actually results in files that are valid per spec (with no padding for the last element) to not be loadable.

KTX1 format, as far as I can tell, includes 4-byte padding in various places but doesn't omit it for the last element.

So it seems like it would make the specification slightly simpler if the conditional padding was replaced with unconditional. I'm not sure if there's a specific rationale for the status quo?

**Comment by MarkCallow** [comment]
PR #114 had to be aborted so this was actually closed by PR #115.
