### ISSUE TITLE
Value for KDF_DF_MODEL_UASTC?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Specification#119]
The specification draft references KDF_DF_MODEL_UASTC, however this is absent in latest revision of Khronos DataFormat 1.3.

**Comment by MarkCallow** [comment]
Yes. The specification draft also says "value to be assigned".  (Updating KDFS has a lot of bureaucratic overhead due to various Khronos WG's normatively referencing the spec.) If you want a value to be working with right now, you can use the next available color model value, 166.

**Comment by zeux** [comment]
Yeah 166 was my best guess :) Thanks!
