### ISSUE TITLE
Caution says half-float have different enum values, mapping doesn't show these

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#125]
@lexaknyazev 

At the top of Appendix A is a caution saying

> Half-Float data type uses different enum values on different OpenGL ES and WebGL versions. 

The format mappings for each of the relevant types give a single enum *name* then the OpenGL, OpenGL ES and WebGL core versions and extensions supporting that type. It does not indicate which of these enum names have differing values. Is the caution accurate?

If the caution is still needed, it should say Half-float not Half-Float.

**Comment by lexaknyazev** [comment]
> Is the caution accurate?

It is. For some reason, the `GL_OES_texture_half_float` extension for OpenGL ES 2.0 (and therefore WebGL 1.0) uses its own enum name and value: `GL_HALF_FLOAT_OES 0x8D61`.

Whereas OpenGL 3.0+, `GL_ARB_half_float_pixel`, `GL_APPLE_float_pixels`, `GL_NV_half_float`, OpenGL ES 3.0+, and WebGL 2.0 all use `GL_HALF_FLOAT 0x140B`.

The mapping template currently doesn't have a way to add version-specific enums.

**Comment by MarkCallow** [comment]
Since the template can't hold the information, please include it in the caution and please change Half-Float to Half-float.
