### ISSUE TITLE
Bring back zlib/deflate scheme enum

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#128]
Deflate support is universal on native platforms.

For the web, [Compression Streams](https://chromestatus.com/features/5855937971617792) WPICG proposal was shipped in Chrome 80 (Feb 2020). Other browsers could use wasm modules to decompress zlib streams.

**Comment by MarkCallow** [comment]
I'm okay with doing this. In spec. terms it's trivial. Now that I've implemented one similar scheme, zstd, I can also say that the extra code for deflating a texture will be ~84 lines and for inflating, ~88 lines so not a big implementation burden.

Should we discuss in the WG?
