### ISSUE TITLE
Reasoning behind the mip ordering to smallest to largest in KTX2?

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/KTX-Specification#132]
Curious why mip ordering was flipped from KTX where it was largest to smallest.  Now it's smallest to largest?  This makes it a little trickier to convert from KTX to KTX2.

**Comment by MarkCallow** [comment]
To make it amenable to streaming. App's can show something after receiving the smallest level and can refine as more data comes in.

**Comment by alecazam** [comment]
I see, nice!  I think with VT (virtual texturing) that mips will also need to have some sort of block breakdown, but maybe KTX2 won't work for that and a production format will be needed.  Also the VT tile size could change per platform.
