### ISSUE TITLE
ktx2ktx2 should be able supercompress KTX files.

### ISSUE THREAD

**Issue by alecazam** [KhronosGroup/KTX-Specification#133]
One idea was to build encoded mips as a KTX file (since there are previewers), and then feed that to ktx2ktx2 to do the supercompression to a KTX2 file.  But ktx2ktx2 just converts the data, fills out the DFD, and flips mip ordering I guess.  If one just wanted zstd/zlib compressed blocks (not Basis LZ) can this be achieved on any input including compressed blocks?  Is supercompression only supported for basis blacks?

The problem with all encoded blocks are that they're not small compared to PNG with deflate and delta encoding.  Using KTX files to store mips is great, and to store compressed blocks.  Further applying compression to the blocks would allow KTX (or KTX2) to be used as a source or destination format. 

There are very few lossless formats otherwise.   PNG is straight 8.  EXR is premul 16f/32f only with deflate.  Tiff is premul and 8/8srgb/16f/32f has a variety of compressors, but Apple's TIFF readers can only parse LZW (not zlib).  And trying to get at the mips of these other formats just adds to the code needed to parse HDR data.  Parsing KTX/KTX2 would seem the lightweight alternative format.

**Comment by MarkCallow** [comment]
You can use `ktxsc` to supercompress a .ktx2 file. It takes exactly the same supercompression (and Basis Universal options) as toktx. You can connect the apps with a pipe

```
ktx2ktx2 -o stdout <foo.ktx> | ktxsc [options] > foo.ktx2
```

Try `ktxsc --help` for the options or `man ktxsc` (if you're not on Windows).

You can apply just zstd supercompression or you can first encode to a universal format and then supercompress.  For obvious reasons you can't encode a texture in a block compressed format to a universal format. However you can supercompress a block-compressed format with zstd.

**Comment by alecazam** [comment]
Ah thanks, Mark.  I hadn't used that ktxsc tool yet.  That's really awesome.

**Comment by alecazam** [comment]
I'll check sources on that, but usage indicates basis and zstd but not zlib supercompression.  That's good enough to start with.

**Comment by MarkCallow** [comment]
zlib is not implemented yet. I'll be happy to take a PR to add it.

Note that we've found zstd to give better compression than zlib.

**Comment by alecazam** [comment]
I think zstd is good.   I've only used a few zlib compressors.  Apple's libCompression has a fast implementation, and Geldreich has minz.  I really like zstd, but haven't seen hw for it, but zstd and lz4 are great for decompression.  Rumors point to PS5 uses Kraken/zlib, and XboxX has zlib hw.  Apple has a lot of effort behind LZFSW which is close to zstd.
