### ISSUE TITLE
Mip-level language clarifications

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#152]
The following issues are relatively minor but still worth fixing.
- [x] The spec does not mention that dimensions of each subsequent mip level are halved compared to the previous one.
- [x] In Section 2, the expressions for `num_blocks_*` do not mention that per-mip dimensions are used there.
- [x] Section 3.13.1 says:
  > When `supercompressionScheme != 0` these bytes are formatted as specified in the scheme documentation.

  However, neither Zlib nor Zstandard scheme notes mention how images are concatenated there. Moreover, the BasisLZ notes technically create a circular reference.

**Comment by MarkCallow** [comment]
Please propose a PR.
