### ISSUE TITLE
Add description and keywords to the repo

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#153]
Please add a short description and keywords in the GitHub settings for better discoverability.

**Comment by lexaknyazev** [comment]
These options are hidden behind the gear icon next to the "About" label on the repo home page.

![image](https://user-images.githubusercontent.com/3479527/137681318-5370096f-d7fd-4410-91cb-4f0586fdc393.png)

**Comment by MarkCallow** [comment]
Thanks. Added.
