### ISSUE TITLE
No support for edge clamp mode and filter mode?

### ISSUE THREAD

**Issue by Leadwerks** [KhronosGroup/KTX-Specification#160]
I was under the impression that KTX2 specified the edge mode (clamp/repeat/mirror) and filter mode (linear/nearest) of the texture, like Valve texture files do, but I can't find any mention of these features here:
https://github.khronos.org/KTX-Specification/ktxspec_v2.html

Is that not supported?

**Comment by lexaknyazev** [comment]
The original issue #38 about storing the sampler config didn't get much traction back when the KTX2 spec was authored. If there's strong interest we could revisit it.

@MarkCallow WDYT?

**Comment by MarkCallow** [comment]
I'm going to close this to keep the discussion in #38 where I will respond.
