### ISSUE TITLE
Confirm prohibited formats

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#163]
From the Section 3.2:
> It can be any value defined in core Vulkan 1.2, future core versions or registered Vulkan extensions, except for values listed in Table 1, “Prohibited Formats” and any `*SCALED*`, `*422*`, `*[2-9]PLANE*` or `*[34]PACK16*` formats added in future.

- The table includes 6 single-plane packed 10- and 12-bit formats like `R10X6_UNORM_PACK16` and `R12X4G12X4B12X4A12X4_UNORM_4PACK16` with no explanation in the rationale section afterwards. Arguably, they could be allowed.
- The wildcard template strings could be slightly optimized: all formats that have `3PACK16` also have `2PLANE` or `3PLANE`.

**Comment by MarkCallow** [comment]
I have have misunderstood what some of those formats really are and thought they were multi-plane.. The intent is to prohibit packed formats that have an equivalent rg, rgb or rgba format, e.g. the *_PACK32 formats, and multi-plane formats.

Happy to accept a PR to modify the list of prohibited formats. An equivalent change must be made to the `lib/mkvkformatfiles` script in the KTX-Software repo which generates the file `vkformat_check.c`. Please create a PR for that too.

**Comment by lexaknyazev** [comment]
OK. In that case, we should also allow single-plane subsampled formats. For reference, here's a full list of currently prohibited single-plane formats.

- 10-bit channels padded to 16 bits:
  ```
  R10X6_UNORM_PACK16
  R10X6G10X6_UNORM_2PACK16
  R10X6G10X6B10X6A10X6_UNORM_4PACK16
  ```
- 12-bit channels padded to 16 bits:
  ```
  R12X4_UNORM_PACK16
  R12X4G12X4_UNORM_2PACK16
  R12X4G12X4B12X4A12X4_UNORM_4PACK16
  ```

- 2x1 blocks (green values are unique, red and blue are duplicated)
  - 8-bit channels
    ```
    G8B8G8R8_422_UNORM
    B8G8R8G8_422_UNORM
    ```
  - 10-bit channels padded to 16 bits
    ```
    G10X6B10X6G10X6R10X6_422_UNORM_4PACK16
    B10X6G10X6R10X6G10X6_422_UNORM_4PACK16
    ```
  - 12-bit channels padded to 16 bits
    ```
    G12X4B12X4G12X4R12X4_422_UNORM_4PACK16
    B12X4G12X4R12X4G12X4_422_UNORM_4PACK16
    ```
  - 16-bit channels
    ```
    G16B16G16R16_422_UNORM
    B16G16R16G16_422_UNORM
    ```

**Comment by MarkCallow** [comment]
Thanks. @fluppeteer DFD-wise are there any problems with allowing these?
