### ISSUE TITLE
Confirm KTXwriter and KTXwriterScParams encoding

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#164]
Unlike other string-based metadata entries, the descriptions of `KTXwriter` and `KTXwriterScParams` do not mention whether the value strings are NUL-terminated.

For the reference, Section 3.11 does not require NUL termination for all string metadata values.

**Comment by MarkCallow** [comment]
It is supposed to be NUL-terminated. Thanks for spotting this. Please submit a PR to fix it.
