### ISSUE TITLE
Consider rephrasing format mapping metadata usage

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#166]
Section 5.3 says:
> When Appendix B, _Mapping of `vkFormat` values_ does not have an entry for the value of `vkFormat`, which will happen for newly added Vulkan formats, the KTX writer must provide any known mapping via the following key-value pairs.

I think there are two issues with this language:
- This text makes the mapping metadata presence normatively depend on the contents of a non-normative Appendix B. Moreover, the Appendix could be modified at any time thus potentially invalidating the existing files.
- This text does not cover the case when the format is representable with DFD and, e.g., OpenGL enums but does not have a Vulkan counterpart. For example, BC5 with reversed order of channels aka ATI2n.

**Comment by MarkCallow** [comment]
I agree it need tightening. Please propose a PR with the rephrasing.
