### ISSUE TITLE
Clarify compressed formats for 1D textures

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#167]
From the OpenGL specs:
> An `INVALID_ENUM` error is generated by `CompressedTexImage1D` if `internalformat` is one of the specific compressed formats.

In Vulkan, there's no explicit prohibition but none of the _Mandatory format support_ tables for the compressed formats include `VK_IMAGE_TYPE_1D`.

The KTX spec should either disallow this case or define how to handle it.

**Comment by MarkCallow** [comment]
We should disallow it.
