### ISSUE TITLE
Is it necessary to mark metadata as "required"?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#17]
It has been suggested that KTX2 should provide a way to mark metadata as required or not. This issue is for tracking that discussion.

**Comment by MarkCallow** [comment]
It is not clear to me what *required* would mean. I think that needs to be clarified before we decide if we need a way to identify such.

One definition might be that a reader needs to understand the metadata in order to correctly load the file. That will lead to a major digressions into what *load* and *correct* mean. For example to load a format from a Vulkan extension requires the loader understand the KTXrequiredvkextension item so it can enable the extension, otherwise loading will fail. But if loading the image for something other than Vulkan/OpenGL, the DFD may well provide sufficient information and the metadata can be ignored.

On the other hand if KTXorientation and KTXswizzle are ignored something can be loaded but it may well not display the intended image - the wrong orientation in the first case, the wrong colors in the second regardless of whether loading to Vulkan/OpenGL or something else.

**Comment by dewilkinson** [comment]
By definition, metadata blocks should be ignorable without breaking the app or the decoder.

However , certain types of metadata could be considered required (I may wish to encode a series of atlas coordinates in my image, for example). In this case, a reader that ignores metadata would break the app.

We would need either a ‘required’ flag in the metadata, or a second ‘global data’ block in the file format using the same key/value container style , representing data that must be parsed.

My concern about a flag within the metadata is you throw away the rule that metadata is purely optional, and that many readers still might not honor the flag and skip the metadata block out of habit.

A separate, mandatory,  global data table of zero or more entries would have my vote

**Comment by MarkCallow** [comment]
In current libktx, the application indicates whether it wants the metadata read or not by a parameter passed to the ktxTexture_createFrom* functions, which are what read the file.

Given that the existing metadata is pretty small, I can't see any need for a flag or a second block of key-value data within the file to enable reading just part of the metadata. Read all or none seems fine.

**Comment by dewilkinson** [comment]
I think this approach would work fine. Alexey , others, any objections?

**Comment by MarkCallow** [comment]
Read all or none is not a problem so closing this.
