### ISSUE TITLE
Confirm mipPadding size

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#175]
The spec says:
> When `vkFormat` is not `VK_FORMAT_UNDEFINED`, _texel block size_ is as given for the `vkFormat` value in
[section 40.1.6 _Format Compatibility Classes_](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#formats-compatibility) of VULKAN12EXT otherwise it is 16.

- We need to make an exception here for `VK_FORMAT_D16_UNORM_S8_UINT` as the Vulkan table defines it as 3-byte while the KTX spec defines it as 4-byte.
- We need to make an exception here for `VK_FORMAT_D32_SFLOAT_S8_UINT` as the Vulkan table defines it as 5-byte while the KTX spec defines it as 8-byte.
- Does it mean that regular RGB formats like RGB8/RGB16/RGB32/RGB64 need 12 (or 24 for the last case) byte alignment?

**Comment by MarkCallow** [comment]
This is about GPU-upload-ready alignment. Since Vulkan requires separate uploads of the depth and stencil components shuffling is going to be required. It is a good idea to require 4 for `VK_FORMAT_D16_UNORM_S8_UINT` so that all the 16-bit values will be on 2 bytes boundaries. Similarly to keep all the floats on 4 byte boundaries it is a good idea to require 8 for `VK_FORMAT_D32_SFLOAT_S8_UINT`.

The answer to the last bullet is yes. That is what modern GPU's require. I distinctly remember dealing with the 12-byte alignment for RGB8 when I was writing `vkupload`.

**Comment by lexaknyazev** [comment]
> It is a good idea to require 4...

Just to clarify, KTX already defines aligned components for `D16_UNORM_S8_UINT` and `D32_SFLOAT_S8_UINT` in Section 3.2.1. However the language in the `mipPadding` section requires use of `lcm(texel_block_size, 4)` which refers to the values from the Vulkan spec yielding 12 and 20 instead of 4.

**Comment by MarkCallow** [comment]
3.2.1 gives the effective KTX texel block size for those formats. The `mipPadding` section should reference those block sizes. You probably only need a 4-byte alignment to upload the D32 component (I haven't checked) but it is simpler to continue with the texel block size concept than introduce an exception.

**Comment by lexaknyazev** [comment]
OK, we can refine the _texel block size_ definition like this:

> _texel block size_ is as given for the `vkFormat` value in [section 40.1.6 _Format Compatibility Classes_](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#formats-compatibility) of VULKAN12EXT for all `vkFormat` values except the following three:
> | VkFormat                       | Texel Block Size |
> |--------------------------------|------------------|
> | `VK_FORMAT_UNDEFINED`          | 16               |
> | `VK_FORMAT_D16_UNORM_S8_UINT`  | 4                |
> | `VK_FORMAT_D32_SFLOAT_S8_UINT` | 8                |

**Comment by lexaknyazev** [comment]
Looking at this again, it seems to me that neither the existing nor the proposed language properly handle `VK_FORMAT_UNDEFINED` case. In such a case, the texel block size should be derived from the DFD rather than always assumed as 16.

**Comment by MarkCallow** [comment]
There was a reason I made it 16. I can't recall at present why. I'll see if I can find any discussion or git log.

`libktx` already calculates the required alignment from the DFD but has an exception for `VK_FORMAT_UNDEFINED` so codewise this change would not be an issue.

**Comment by lexaknyazev** [comment]
Were you able to find something? Maybe this exception was made for UASTC (before the DFD update)?

**Comment by MarkCallow** [comment]
No I haven't found anything concrete. I think it is okay to calculate the alignment from the block size given by the DFD.
