### ISSUE TITLE
KDF_DF_* vs KHR_DF_*

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Specification#186]
The specification currently refers to near-identical enum values with both `KHR_DF_*` and `KDF_DF_*` prefixes:

- KDF_DF_MODEL_UASTC
- KHR_DF_MODEL_UASTC
- KDF_DF_MODEL_ETC1S
- KHR_DF_MODEL_ETC1S

Is this intentional? I'd be happy to make a PR if not. Just found a bug in my code resulting from copy/pasting these values and ending up with two names for the same thing. Thanks!

**Comment by lexaknyazev** [comment]
Good catch! It must be `KHR_DF_` everywhere.
