### ISSUE TITLE
Reserve vendor ID for super-compression scheme

### ISSUE THREAD

**Issue by JulienVernay-AsoboStudio** [KhronosGroup/KTX-Specification#194]
Hello,
I am Julien Vernay, Engine Programmer at Asobo Studio, France.
We would like to use KTX2 in our toolchain, with a proprietary super-compression scheme.
Thus, we need to have a unique ID for the 'supercompressionScheme' field.
Is it possible to have one?
If needed, we have the ASOBO vendor prefix in glTF.

**Comment by MarkCallow** [comment]
> Is it possible to have one?

Yes. You are the first to request one so bear with me for a few days while I get a place set up in the KTX Registry to record the information.

**Comment by MarkCallow** [comment]
@JulienVernay-AsoboStudio please register your scheme via a PR as described in [these instructions](https://github.com/KhronosGroup/KTX-Specification/blob/main/ktxspec.adoc#434-registering-extensions).

**Comment by MarkCallow** [comment]
Done in commit 98043e1eca936938159b5be67e7e5855b8d4883b.
