### ISSUE TITLE
Provide formal syntax for KTXorientation metadata

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#20]
The spec gives some examples and descriptions, but there's no formal parsing process defined.
Here's a list from the spec:
```
-   S=r,T=d
-   S=r,T=u
-   S=r,T=d,R=i
-   S=r,T=u,R=o
```

A robust parser for this kind of syntax has to cover lots of edge cases like:
```
-   S=r,S=l // overriding S
-   S=u // wrong value for S
-   S=r, // trailing comma
-   S=r, T=u // space after comma
-   S=r,Q=z // unknown parameter
-   R=o,T=u,S=r // inverse order of dimensions
-   T=r // S orientation is undefined
```
Follow-up questions:
- Is it valid to define all 3 orientations for 1D/2D textures?
- Is it valid to under-define orientations for 2D/3D textures?

---

To simplify implementations, I propose to change this syntax like this:
- **1D**: exactly one byte: `{r,l}`.
- **2D**: exactly two bytes: `{r,l}{d,u}`
- **3D**: exactly three bytes: `{r,l}{d,u}{o,i}`

**Comment by MarkCallow** [comment]
@lexaknyazev in your proposed syntax are you getting rid of the "S=" etc?

Please propose a "formal parsing process" for the spec.

**Comment by lexaknyazev** [comment]
Yes, in my proposal above the whole value consists of 1..3 bytes, so there can be only 14 valid values:
```
r
l
rd
ru
ld
lu
rdo
rdi
ruo
rui
ldo
ldi
luo
lui
```

Looking at this again, I'd go even further by compressing all of them into one byte with even simpler parser:
```c
/// Value is a one byte bitfield defined as 00000RTS.
/// When orientation is not applicable to the 
/// texture (e.g. R for 2D), bit must be set to 0
int v = read_byte();
if (v & 1) {
  // S = l
} else {
  // S = r
}

if (pixelHeight > 0) {
  if (v & 2) {
    // T = u
  } else {
    // T = d
  }

  if (pixelDepth > 0) {
    if (v & 4) {
      // R = i
    } else {
      // R = o
    }
  }
}
```

**Comment by lexaknyazev** [comment]
@MarkCallow 
What do you think about my latest (one-byte) proposal for image orientation metadata?

**Comment by MarkCallow** [comment]
I prefer the 1 to 3 letter variant. The spec currently says UTF-8 strings are preferred as metadata values. I accepted the bitfield for issue #11 because that seems the most reasonable way to handle that situation. Here the letters are fine.

**Comment by lexaknyazev** [comment]
OK. So my proposal for the updated spec is:

---

Value is a nul-terminated string formatted depending on the texture type.

| Type | Format |
|------|------------------|
| 1D | `^[rl]$` |
| 2D | `^[rl][du]$` |
| 3D | `^[rl][du][oi]$` |

where

- **r** indicates S values increasing to the right
- **l** indicates S values increasing to the left
- **d** indicates T values increasing downwards
- **u** indicates T values increasing upwards
- **o** indicates R values increasing out from the screen (moving towards viewer)
- **i** indicates R values increasing in towards the screen (moving away from viewer)

When a texture is an array, all its elements have the same orientation.

Values not matching the table above are invalid.

It is recommended that viewing and editing tools support at least the following values:

- `rd`
- `ru`
- `rdi`
- `ruo`

**Comment by MarkCallow** [comment]
Looks good to me. We should make KTXswizzle match this style too, i.e. get rid of the R=, G=, etc.
