### ISSUE TITLE
Depth/stencil textures support

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#24]
We need to verify whether KTX2 needs to support depth and/or stencil textures.

If it does:
- Which texture types could be used with D/S data?
- How does swizzling interact with D/S?

**Comment by MarkCallow** [comment]
KTX2 should support depth and stencil textures. Is there any reason not to just use the _D* and _S* Vulkan formats? As for swizzle, in Vulkan it only applies to "depth or stencil components after they have been converted to color components." I'm not sure how you do the conversion. I suggest KTXswizzle is not allowed for depth & stencil formats.

**Comment by lexaknyazev** [comment]
We should carefully investigate texture type compatibility and whether it's allowed to upload textures of certain formats. A few examples:
- A texture cannot be of 3D type (at least in OpenGL, probably true for all platforms).
- `VK_FORMAT_D16_UNORM_S8_UINT` is unique to Vulkan and has 3-byte width (quite unusual).
- `VK_FORMAT_D32_SFLOAT_S8_UINT`:
  - 5 or 8 bytes per texel in Vulkan (not sure how this applies to uploading):
  > 32 signed float bits in the depth component and 8 unsigned integer bits in the stencil component. There are optionally: 24-bits that are unused.
  - 8 bytes per texel in OpenGL (with glType `FLOAT_32_UNSIGNED_INT_24_8_REV`), Metal, and DX.
  - Unavailable for upload in WebGL 2.0.

+1 for disallowing swizzling.

**Comment by dewilkinson** [comment]
Note that this could be bundled in with the Deep Pixels (multisampling/per-pixel-layers), should the group decide to incorporate it.

Eg. Refer to the link below as to how OpenEXR handles texture resources that may have multisample , depth, stencil , or auxiliary layers

http://www.openexr.com/documentation/InterpretingDeepPixels.pdf

**Comment by MarkCallow** [comment]
KTX2 should support depth/stencil textures in a way that matches the APIs. Since the APIs have ways to load them, it should be possible store them in a KTX2 file. Deep Pixels is a separate issue that may or may not also include depth/stencil pixels.

**Comment by dewilkinson** [comment]
Agreed to support clearly defined DS formats, however there are ambiguous depth formats that allow a variable number of bytes to be assigned for depth (up to 5?), but it is not clear how to represent these in the DFD

Action item: Alexey is chasing up info from Vk WG

**Comment by lexaknyazev** [comment]
From Vulkan spec and internal discussions:
> To copy both the depth and stencil aspects of a depth/stencil format, two entries in `pRegions` can be used, where one specifies the depth aspect in `imageSubresource`, and the other specifies the stencil aspect.

> you have to have two separate (planar) buffer regions, one with depth data, one with stencil.

This means that it's impossible in Vulkan to upload interleaved depth/stencil texels.

Our options for KTX:
- Disallow combined D/S formats.
- Require Vulkan loaders to manually rearrange texels on upload.
- Store depth and stencil data separately, require non-Vulkan loaders to combine texels on upload.

**Comment by MarkCallow** [comment]
In the non-Vulkan APIs is it really not possible to upload just depth or just stencil to a texture of the combined format?

The 1st & 3rd options are the same.

I'm tempted to say disallow but as WebGL and OpenGL {,ES} are deployment targets we should try to find out if there is widespread use.

**Comment by lexaknyazev** [comment]
> The 1st & 3rd options are the same.

Not quite. With the third option, we can "re-define" the layout so that components are not interleaved. In that case, Vulkan loaders would be able to use two adjacent `pRegions`.

**Comment by MarkCallow** [comment]
Since in Vulkan these must be loaded via a staging buffer, option 2 is straightforward to implement while the data is copied into the staging buffer. It will not be much slower than copying a single block of data into the staging buffer.

I cannot see any way to load separate depth and stencil into OpenGL, except by having an additional combining step.

So I am leaning toward option 2, allowing the combined formats, with the proviso that `VK_FORMAT_D32_SFLOAT_S8_UINT` includes the optional-in-Vulkan 24 bits so it is compatible with OpenGL, Metal and DX. Hopefully supercompression can help reduce the effect of those extra 24-bits per pixel.

**Comment by lexaknyazev** [comment]
OK.

So, here's a full list of D/S formats with their runtime implications:

- **`VK_FORMAT_D16_UNORM`**, **`VK_FORMAT_D32_SFLOAT`**
  - All APIs. Single-block upload.
- **`VK_FORMAT_S8_UINT`**
  - No D3D support. Single-block upload.
- **`VK_FORMAT_X8_D24_UNORM_PACK32`**
  - No native support in Metal and D3D. Single-block upload.
  - [ ] We must include a note regarding layout (this one is taken from Vulkan, and if I understand correctly, it should be compatible with OpenGL; "undefined" should be changed to "zero" for better compression):
    > one 32-bit word per texel with the D24 value in the LSBs of the word, and undefined values in the eight MSBs
- **`VK_FORMAT_D16_UNORM_S8_UINT`**
  - Vulkan-only. Components have to be extracted and uploaded separately.
  - [ ] We must include a note regarding layout, **that is not defined anywhere** currently.
- **`VK_FORMAT_D24_UNORM_S8_UINT`**
  - All APIs. Components have to be extracted and uploaded separately in Vulkan.
  - [ ] We must include a note regarding layout (this is taken from OpenGL; D3D and Metal compatibility has to be verified):
    > one 32-bit word per texel with the S8 value in the LSBs of the word, and D24 value in the MSBs

    > ![image](https://user-images.githubusercontent.com/3479527/51740762-60af2480-20ae-11e9-857b-7d4072be006f.png)
- **`VK_FORMAT_D32_SFLOAT_S8_UINT`**
  - All APIs. Components have to be extracted and uploaded separately in Vulkan.
  - [ ] We must include a note regarding layout (this is taken from OpenGL; D3D and Metal compatibility has to be verified):
    > 8 bytes per texel. 32-bit floating point depth value followed by 32-bit word with the S8 value in the LSBs of the word, and zeros (for better compression) in the MSBs

    > ![image](https://user-images.githubusercontent.com/3479527/51741010-15e1dc80-20af-11e9-8b42-64a364bc43e5.png)

**Comment by MarkCallow** [comment]
Thanks @lexaknyazev. This is great. This info should be added to the ever growing `vkFormat` section of the spec. The mappings should be added to the table you are building. Please make a PR to do these things.

Since Vulkan does not give an exact layout for the combined formats, we'll have to do specify what they are. 

> - **`VK_FORMAT_D16_UNORM_S8_UINT`**
>  - Vulkan-only. Components have to be extracted and uploaded separately.
>  - [ ] We must include a note regarding layout, **that is not defined anywhere** currently.

It's 3 bytes, tightly packed. Given the naming it is logical to say the 16 depth bits are in the first 2 bytes and the S8 in the 3rd byte.

**Comment by MarkCallow** [comment]
Yes it would because the D16s will then be 16-bit-aligned. That brings the question should we use the Vulkan enum name or should we use VK_UNKNOWN_FORMAT and the DFD? Using the Vulkan enum name seems simpler.

**Comment by lexaknyazev** [comment]
+1 for existing enum.

**Comment by lexaknyazev** [comment]
Looks like CTS uses padded layout internally as well: 
https://github.com/KhronosGroup/VK-GL-CTS/blob/f29af633426235c155b7a33c2f2cf18a51d1ac1b/external/vulkancts/framework/vulkan/vkImageUtil.cpp#L1851

**Comment by MarkCallow** [comment]
Should we treat `VK_FORMAT_D32_SFLOAT_S8_UINT` as a 64-bit value or 2 32-bit values? The answer will affect endian conversion.

Please don't forget to create the PR mentioned above. The PR may need to fix `typeSize` depending on our decision re. the above as it will state, as of the next PR I'm about to merge, that typeSize should be 4.

**Comment by lexaknyazev** [comment]
As two 32-bit values. OpenGL spec doesn't seem to suggest that it's a 64-bit type. Vulkan requires separate uploads anyway.

**Comment by MarkCallow** [comment]
Great thanks.
