### ISSUE TITLE
Support multi-sample images?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#27]
Over the years I've received several requests to support multi-sample images in KTX. Since it was not possible, without breaking compatibility, I never pursued details of what the requesters wanted.

We will ask the Vulkan Advisory Panel for insights but any other comments on this topic are welcome.

**Comment by dewilkinson** [comment]
I’m having a hard time finding ISVs who would actually utilize this for real-time graphics. The only perceived use would be complex shader based compositing operations - something we’d see in a movie studio tools pipeline, but not typically in real-time graphics. We need to identify if this feature is In scope , and identify some solid use cases of this.

With that said, there may be use for some layered pixel structure for optional inclusion of depth, stencil , alpha or non-RGB auxiliary channels. Which could be utilized for multi sampling , and be generally more useful.

This would add complexity though. See link to OpenEXR Deep Pixel link below for some of the functionality we’d need to support 

http://www.openexr.com/documentation/InterpretingDeepPixels.pdf

**Comment by MarkCallow** [comment]
The link talks about each "sample" is associated with a depth from the viewer; it also says each each pixel can have a different number of "samples". Neither of these things sound like what I understand by multisample images.

Let's see what the VAP survey tells us before we spend any more time on this.


I was going to ask how does this differ fundamentally from a 3D texture (in terms of the structure of a KTX2 file) but then I spotted the part saying

**Comment by MarkCallow** [comment]
A possible use case, Grand Turismo has a Scape mode where the use can render an image of their racer over a high res background landscape. Currently they use very large images (6k x 8k). They could use multi-sample images for these 'scapes.

**Comment by dewilkinson** [comment]
Mark, I can't seem to edit this. Could you add a 'Resolve before trial'. We want to make sure we include any necessary stubs and all structures are futureproof should we implement this in a future revision. At the very least we will need to keep numSamples, a samplemask dword, and a way to cleanly allow for layers or multisample texel structures to be integrated in future

**Comment by MarkCallow** [comment]
My excitement was premature. The extension does not say anything about glTexSubImage or uploading data to these textures. The extension is in 4.6 Core as are glTexImage[23]DMultisample which predate the extension. They have no `data` parameter so uploading is not possible.

**Comment by dewilkinson** [comment]
After several discussions with both potential stakeholders in this feature , along with GPU hardware architects. I would like to propose that we abandon this idea, or at least shelve it for now.

We did find one compelling use case from the authors of Gran Turismo , where they load huge supersampled HDR images into video memory to act as a background far sky plane - upon which 3D game assets were composited. 

So yes, this would be a great example where a multisampled source image could be utilized to save resolution and bandwidth

BUT, The blocking issues are as follows:

- source image Sample patterns must match he sample patterns. Not all hw can do this

- Main APIs have no way to copy a multisampled buffer directly in GPU memory. At best a shader stage would be required

- BUT internal GPU memory layout of multisampled surfaces vary across GPU devices , and this layout is proprietary 

With the above caveats, the only possible way to guarantee correct behavior would be to perform composition objects in software with potential shader assist, submitting to the GPU pipeline is not an option.

In my opinion this makes the KTX2 multisampled export proposal out of scope for GPU Texture Transmission

I would propose we vote to close this unless there are further arguments why it should be supported.

**Comment by MarkCallow** [comment]
Agreed.
