### ISSUE TITLE
Purpose of levelOrder field?

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#28]
ISVs have requested clarification of why levelOrder needs to be specified? Can the order not just be fixed to highest->lowest mip? This way low bandwidth apps can take advantage of streaming low-to-high resolutions, and desktop apps can choose for themselves which level(s) to pull in

**Comment by MarkCallow** [comment]
I think fixing the order smallest to largest would be okay.

**Comment by dewilkinson** [comment]
Reviewed on 12/21 call

Agreed. Level sequence should always be highest to lowest mip, no order field is required.

Rationale:
Mobile devices can stream in smaller levels first, and stop decoding at max desired resolution

Desktop devices read the whole file in anyway and can extract the levels in any order they wish using index tables

**Comment by MarkCallow** [comment]
I started to look at fixing this and realized that KTX 1 supports, and we had requests for KTX 2 to also support, partial mipmap pyramids. In such a case I expect that you'd want to start from the base level (level 0) as in KTX 1 so the single `numberOfMipmapLevels` field was sufficient. If we always order from max level, and we want to support incomplete pyramids, I think we'll need min and max level fields or else keep the `levelOrder` field. Would there ever be a reason to have levels somewhere in the middle of the pyramid or from max level to somewhere in the middle?

Thoughts?

**Comment by lexaknyazev** [comment]
Could max level be figured out from `numberOfMipmapLevels` and dimensions? 
For what reason one may omit the base level?

**Comment by MarkCallow** [comment]
Fixed by PR #46.

**Comment by MarkCallow** [comment]
I made some additional improvements in PR #47.
