### ISSUE TITLE
Fix padding issues

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#31]
ISV feedback:

“All this padding madness – can’t we just enforce that everything is 4-byte aligned and be done with it, and every “section” is 16-bytes aligned? Why does the previous section need to pad? Wouldn’t it be easier to just require that a section starts at an aligned position and have an offset stored to it? It seems weird that padding bytes are specifically spelled out in the specification. At the very least, I would expect padding bytes to be defined to be 0 to ensure that there is no ambiguity.”

**Comment by MarkCallow** [comment]
The padding bytes are defined to be zero. See issue #10.

I can't see that it makes how difference how we specify where the padding bytes are. If we take this suggestion we have to define what a section is. Resolution of some other issues, particularly issue #32 & issue #33 will likely affect this issue.

**Comment by MarkCallow** [comment]
We want checksums and hashes to give the same values for the same content and binary diffs to match. It's one reason we specified that padding bytes must be 0. If we do change the spec. along the lines suggested here, we need to ensure there isn't wiggle room for the amount of padding to differ while still meeting an alignment requirement.

**Comment by dewilkinson** [comment]
Reviewed in 12/21 call, consensus was that the current spec wording should remain as is. We do not want identical files to have different sizes and hashes purely because of arbitrary alignment differences

Closing as won’t fix

**Comment by MarkCallow** [comment]
Alignment differences wasn't the issue. It was differences in the amount of padding while still retaining a specified alignment. Because we need the amount to be consistent any spec wording changes will not result in any change to the bits in a file and improvements in spec readability, if any, will be marginal.
