### ISSUE TITLE
Better ASTC support

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#37]
ASTC texture formats cover lots of use-cases and KTX2 spec requires additional details to fully support them.

`vkFormat` (as well as `glFromat`) gives only three properties of ASTC data: 
 * Block dimension (2D or 3D)
 * Block footprint size (4x4, 5x4, ...)
 * sRGB output enabled or not

**Blocking issue:**
- There's no Vulkan enums for ASTC 3D blocks. 
  - [ ] @dewilkinson or @MarkCallow, could you ask Vulkan WG about this?

**Not every format value is valid for every possible KTX2 dimensions configuration.** Moreover, LDR/HDR modes are signaled  _per-block_ within texture data.

- ASTC is not supported for 1D textures.
  - [x] This is already enforced by KTX2 dimensions restrictions.
- There are additional constraints based on block sizes - i.e., `pixelWidth` must be a multiple of block's width.
  - [x] We can enhance `pixelWidth` and friends section with that because it's relevant for all block formats.
- Implementations supporting only LDR profile (without `_sliced_3d` extension) will not accept ASTC for 3D texture targets.
  - [ ] Not a file format issue, but maybe it's worth mentioning.
- sRGB formats cannot contain blocks with HDR modes (decoder will output error color).
  - [x] We can use DFD to tighten this. See (section 7.5):
    >  ... an ASTC texture that is guaranteed by the user to contain only LDR-encoded blocks should have the `channel_id` `KHR_DF_SAMPLE_DATATYPE_FLOAT` bit clear, ...
- Some recent mobile GPUs support reducing ASTC's decoder precision for better cache performance and power saving. While the encoded data remains the same, the exact decoded bits will be different, so some pipeline tools may want to keep this information.
  - [x] If there's enough interest, we can add a new metadata entry (see `VK_EXT_astc_decode_mode` or `EXT_texture_compression_astc_decode_mode`).

**Comment by MarkCallow** [comment]
> It appears to be the same in Vulkan

It may not be. I'm checking...

**Comment by lexaknyazev** [comment]
>I have not been able to find the `sliced_3d` extension. Is this a GL extension?

Yes, it's called `KHR_texture_compression_astc_sliced_3d`. I didn't manage to find any info re Vulkan support.

> `VK_EXT_astc_decode_mode` looks to me like the way to enable true LDR...

Since the source LDR data is unorm8 anyway, enabling this extension with `decode_unorm8` should only eliminate possible "higher-precision" artifacts introduced by ASTC codec. So probably, engines should always enable `decode_unorm8` when a texture is LDR-only.

> RGB5E9 limits endpoint values to > 0 so it will be valuable to have metadata for pipeline tools...

Tools should also be aware that this mode always outputs alpha channel as 1.0. Considering these limitations, runtime usage of this mode is more content-dependent and it looks to me like it makes sense only for HDR data. So a texture that is compatible with this decoding mode (i.e., opaque and containing HDR blocks with non-negative values) should have corresponding metadata.

**Comment by MarkCallow** [comment]
`KHR_texture_compression_astc_sliced_3d` adds sliced 3d support to the LDR profile. The HDR profile already supports it. For KTX2 we should allow both LDR and HDR textures to have 3d slices. It will be up to the application to make sure the necessary extension is present before loading.

I'm talking to people at ARM right now about Vulkan extensions.

**Comment by MarkCallow** [comment]
I clarified some of this in PR #40. What's left is to add the width, height & depth must be a multiple of the block size limitation and the metadata to indicate compatibility with RGB5E9 decoding. @lexaknyazev, please create a PR adding these.

**Comment by MarkCallow** [comment]
Block size limitations added sin PR #65 so removing "resolve before trial".

Leaving this open to remind us to modify space as necessary when there are Vulkan extensions for ASTC HDR & 3D VkFormats.

**Comment by MarkCallow** [comment]
This is done except for a spec. update when ASTC HDR & 3D enums are available. OPened a separate issue #84 for that.

**Comment by lexaknyazev** [comment]
> Since the source LDR data is unorm8 anyway, enabling this extension with `decode_unorm8` should only eliminate possible "higher-precision" artifacts introduced by ASTC codec. So probably, engines should always enable `decode_unorm8` when a texture is LDR-only.

This is not necessarily the case. ASTC LDR non-sRGB blocks are decoded with float16 precision and could in theory be compressed from `unorm16` source data (think normal maps).

Should we change `KTXastcDecodeRGB9E5` metadata to a more flexible `KTXastcDecode` with two possible values: `rgb9e5` and `unorm8`?

**Comment by MarkCallow** [comment]
Sounds good to me. Please open an issue specific to this and can you do a PR?

**Comment by lexaknyazev** [comment]
Opened #102.
