### ISSUE TITLE
Relocate Supercompressed Global Data to start of bitstream block

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#39]
It has been decided to remove the binary Global Data block from the current location under the header of KTX2 file, and move it to its own block at the start of the bitstream data, immediately before the highest mip level data offset. The datastream will therefore look like this:

<start texturedatablock>
Pos 0: Supercompressed Global Data [n]
Pos n:  Miplevel m [n(m)]
Pos n + n(m) : Miplevel m-1 [n(m-1)]
Pos n  + n(m) + n (m-1): .......
...
<end texturedatablock>

**Comment by MarkCallow** [comment]
This is fine but I still plan to include the offset to it in the index which I thought was the understanding we had reached.

**Comment by dewilkinson** [comment]
Yes, absolutely, this should have been included in the above resolution. Offset will still be required

**Comment by dewilkinson** [comment]
Mark: what label do we switch to when issue is resolved, but waiting for implementation?

**Comment by MarkCallow** [comment]
None. The fact that it is still open indicates awaiting implementation or fix.

**Comment by MarkCallow** [comment]
I'll be fixing issue #32 along with this in a single change.

**Comment by MarkCallow** [comment]
Please review PR #53.

**Comment by MarkCallow** [comment]
Fixed by PR #53.
