### ISSUE TITLE
Confirm supported ENV_MAP formats

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#41]
ISV request to clarify what formats we support for environment maps

**Comment by lexaknyazev** [comment]
@dewilkinson What exactly does it mean? KTX2 stores texture data in API-supported GPU-ready formats.

**Comment by MarkCallow** [comment]
And it supports cubemaps and cubemap arrays.

I can't see anything to clarify. KTX2 is at a level below this question. It provides the blocks needed to build whatever answer the application wants to use.

**Comment by dewilkinson** [comment]
This was a question from an ISV asking if environment maps were fully supported. Ie. Including HDR and all compressed formats.

Assuming we have all Vulkan and DX formats available and valid for use with cubemaps then it sounds like we’re covered.

I’ll reply to the ISV saying KTX2 supports environment mapping APIs
