### ISSUE TITLE
[Discussion] Allow for multiple copies of the same image to be transmitted in one KTX2 file

### ISSUE THREAD

**Issue by dewilkinson** [KhronosGroup/KTX-Specification#42]
Earlier last year we reached a verbal consensus that a KTX2 file could contain multiple encodings of the same image file. This would be an option for when ETC1S transcodable format is not suitable, ie for lossless images or content that is not well suited for block compression.

The size of the file will obviously be larger with these multiple representations, but it will likely still be required

Note that we would not be permitted to use this technique to transmit multiple different images, such as packaging up all textures used by a material (albedo, normals, specular etc.)) as that would break the glTF material model (noted by Alexey)

**Comment by lexaknyazev** [comment]
I'd say that such functionality should be available only as a part of CRN-style supercompression scheme, i.e. be a part of a decoder API rather than a file format. Different representations (formats) of the same image should be stored in separate KTX2 files.

**Comment by dewilkinson** [comment]
So to clarify, the encoded datastream could embed multiple image encodings implicitly? For example, an ETC1S-CRN block followed optionally by a native ASTC6x6 encoded texture (assuming we are unsuccessful in designing a real-time Transcoder) would basically ‘fill in’ for missing transcoders to give users access formats that we otherwise couldn’t transmit in the CRN format (we would likely want to do this with hard edge WebGL or UI texture content also)

This would abstract messy cases like this out of the file format, so I’d be for this approach.

Agreed that explicit multiple versions of the same file could then go in separate container files.

**Comment by MarkCallow** [comment]
I'd prefer if the glTF file referenced a KTX file per encoding. The client can then decide which one to download. A downside, possibly, is that it makes it impossible to pretend there is some transcoding magic going on. On the upside it will make it obvious why encoding of the texture is taking twice as long as expected.

**Comment by dewilkinson** [comment]
The user would indeed see slower decode performance and larger bitstream lengths if we ‘piggy back’ non transcodable compressed streams onto the same data stream 

I feel this may also cause messy issues with future designs . If we can notify user that they must request a separate KTX for ASTC6x6 for v1.0, it has my vote

PS. There is still no practical transcoding solution for 6x6, 12x12 - I’m tempted to use native encodings for 1.0 and push this issue forward while we examine true use cases and solve the technical issues

**Comment by MarkCallow** [comment]
+1 for using native encodings for 1.0.

How to notify the user to request a separate KTX? Documentation the spec? Something in the glTF file? Something else?

**Comment by MarkCallow** [comment]
CTTF TSG telecon 5/20/19. This would complicate the format beyond its utility.  glTF has a mechanism for providing alternative formats. Anyone wanting to do similar natively should follow a similar model such as a file that lists available formats for a texture.
