### ISSUE TITLE
Streamline build process

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#50]
- Why does `TODO.md` need to be updated with the latest `git log` date given that it never gets published?

- `inlineimages.pl` could be rewritten in Ruby given that Ruby is required for Asciidoctor anyway. This would reduce the number of build deps: `perl` and `base64`.

**Comment by MarkCallow** [comment]
I don't know Ruby but if you want to rewrite inlineimages, please go ahead. Both perl & base64 are standard commands on the macOS environment being used for the CI build so haven't been an issue for me. What environment are you using @lexaknyazev?

TODO.md doesn't need to be updated on CI. Do you know of any automated way that works so when viewing TODO.md on GitHub a last-edited date will be displayed in the file?

**Comment by lexaknyazev** [comment]
I'm going to write an Asciidoctor extension for building formats table from JSON, so it's not to much of a bother to rewrite `inlineimages` as well. In my opinion, 653c2bcc0ea6e738fe6a55553190aa77937dd409 justifies this.

> Do you know of any automated way that works so when viewing TODO.md on GitHub a last-edited date will be displayed in the file?

Within GitHub Pages, Jekyll template `{{ site.time }}` could be used in Markdown. This doesn't apply to regular preview on GitHub.

Is modified TODO.md supposed to be seen only locally?

**Comment by MarkCallow** [comment]
So you're going to re-write base64 as well?

> Is modified TODO.md supposed to be seen only locally?
Yes.

**Comment by lexaknyazev** [comment]
Yes, it's easy.

**Comment by MarkCallow** [comment]
@lexaknyazev most of the URLs that need to be processed are in docinfo.html. Can an Asciidoctor extension for `inlineimages` cope with those? At present Asciidoctor just copies the docinfo.html contents, after processing by `inlineimages`, into the document.

**Comment by lexaknyazev** [comment]
In #51, rewriting URIs is implemented in a post-processing stage, right before writing final HTML to disk.

**Comment by MarkCallow** [comment]
Closed by PR #51.
