### ISSUE TITLE
Clarify KTXglFormat usage for compressed formats

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Specification#52]
The metadata entry provides three enums, while compressed formats need only one.
The spec must say which field must be used and what values must unused fields have.

**Comment by lexaknyazev** [comment]
FWIW, I'd say that compressed enum values should use `glInternalFormat` and two other fields must be zeros.

**Comment by MarkCallow** [comment]
Agreed. Please make a PR.
