### ISSUE TITLE
`keyValuePadding` spec. is wrong.

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#69]
`keyValuePadding` is described as

```c
keyValuePadding[7 - (bytesOfKeyValueData + 7) % 8]
```

but the number of padding bytes needed depends on the length of the preceding Data Format Descriptor, which is guaranteed to be a multiple of 4 only, and the length of the keyValue data. `keyValuePadding` should be renamed to ... oh how about, `align8Padding` which should be

```c
align8Padding[7 - ( bytesOfDataFormatDescriptor + bytesOfKeyValueData + 7) % 8]
```

**Comment by lexaknyazev** [comment]
To avoid all these potentially confusing names, we could rewrite all "padding" fields as pseudo-commands that operate relative to the current position in file, like:
```
// Key/Value Data 
continue
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
    align(4);
                    ︙
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
until bytesOfKeyValueData read
align(8);

// Supercompression Global Data 
Byte supercompressionGlobalData[bytesOfSupercompressionsGlobalData]
align(8);
```

**Comment by MarkCallow** [comment]
I like the idea. I do however need to refer specifically to a couple of these bits of padding: valuePadding and mipPadding, as they are now. I need to say that they are included in bytesOfKeyValueData and bytesOfUncompressedImages respectively. (NOTE: the latter does not currently include mipPadding. That is an error.) Would it be too weird to write
```
// Key/Value Data 
continue
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
    align(4) valuePadding
                    ︙
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
until bytesOfKeyValueData read
align(8);
```
? Any other ideas?

**Comment by MarkCallow** [comment]
I'm also looking for a cleaner way to express the notion that, e.g, valuePadding above, only occurs between keyAndValue pairs but not after the last one. That is what I was trying to show by having the first 3 lines after the continue being optional (greyed-out). Better solutions welcome.

**Comment by lexaknyazev** [comment]
`valuePadding` being included in `bytesOfKeyValueData` but occurring only between metadata entries is quite confusing to me wrt the last entry the size of which supposedly doesn't include the subsequent 8-byte alignment padding.

I'd leave `align(4)` for all entries:
```
// Key/Value Data 
continue
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
    align(4) valuePadding
until bytesOfKeyValueData read
align(8);
```

**Comment by lexaknyazev** [comment]
Alternatively, the order of these fields could be changed so that 4-byte padding exists only between entries:
```
// Key/Value Data 
continue
    align(4) keyValuePadding // always zero first-time
    UInt32   keyAndValueByteSize
    Byte     keyAndValue[keyAndValueByteSize]
until bytesOfKeyValueData read
align(8);
```

**Comment by MarkCallow** [comment]
Thanks @lexaknyazev. I may go with your latter suggestion.
