### ISSUE TITLE
Support GIF-style animation?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#70]
Should we make changes to allow a .ktx2 files to contain an animation, i.e indicate that the set of images is to be displayed sequentially?

An immediate question I have is why do people still use animated GIFs vs. some video file format? Is it about lack of video authoring tools or difficulty dealing with cross-platform video on the Web or something else?

This would be a ktx2 file with  levels=1, faces=1 and layers=<number of frames>. Support is probably just a case of adding suitable metadata that indicates the layers should be displayed sequentially and specifying the interval between frames.

If the sequences are expected to be short, one can even imagine uploading the entire contents to the GPU as an array texture, redrawing at the appropriate interval, incrementing the third texture coordinate in between. It could probably be done entirely on the GPU.

**Comment by lexaknyazev** [comment]
> why do people still use animated GIFs vs. some video file format

GIF - is a well-known term (outside of tech-savvy folks) that means short, looped, muted video fragment. Many web services that provide, show, or host GIFs are actually using MP4 (with H.264) because of obvious storage/transmission reasons.

The issue with video files is the H.264 decoder on mobile platforms. Software implementations may require too many CPU cycles, while hardware decoders may be unable to play more than one video at the same time.

It adds almost nothing in terms of KTX2 complexity to support a new metadata entry like:
```
uint32 duration
uint32 timescale
bool isLooped
```

Two time-related fields are required to accurately represent framerates of existing video content:

| FPS | `duration` | `timescale` | Interval (ms) |
|--------|-----------------|-------------|----------------------|
| 60 | 1 | 60 | 16.667 |
| 59.94 | 1001 | 60000 | 16.683 |
| 50 | 1 | 50 | 20.000 |
| 30 | 1 | 30 | 33.333 |
| 29.97 | 1001 | 30000 | 33.367 |
| 25 | 1 | 25 | 40.000 |
| 24 | 1 | 24 | 41.667 |
| 23.976 | 1001 | 24000 | 41.708 |

**Comment by MarkCallow** [comment]
Why separate duration & timescale values rather than a single millisecond float value or uint32 nanosecond value for the interval?

**Comment by lexaknyazev** [comment]
It just happens to be the case with video formats: they either use 2 integer values to represent time units or define a fixed timescale that has enough frequency to represent most common rates using integer numbers. Following the latter approach, we could choose 120000.

A few examples:
- MP4: uint32 timescale, uint32 duration for each frame
- MPEG2-TS: fixed timescale of 27000000, integer timestamps for each frame
- FLV: fixed timescale of 1000, int32 timestamp for each frame
- WebP: fixed timescale of 1000, uint24 duration for each frame
- APNG: per frame duration and timescale uint16 values
- GIF: fixed timescale of 100, uint16 duration for each frame

On a side note, `bool isLooped` should be changed to `uint loopCount` with `0` meaning unlimited.

**Comment by MarkCallow** [comment]
> FLV: fixed timescale of 1000, int32 timestamp for each frame

? How can you timestamp a multi-hour video with this fixed timescale?

Seems like a lot of complexity. A uint16 could hold any of the frame intervals you listed expressed as nanoseconds: 16,667 to 41,708. But it its what the video people want...

**Comment by lexaknyazev** [comment]
> > FLV: fixed timescale of 1000, int32 timestamp for each frame
> 
> ? How can you timestamp a multi-hour video with this fixed timescale?

The video would need to be longer than 596 hours for int32 timestamp to overflow. I don't think that FLV files were expected to be that long. The value would certainly wrap to 0 and continue incrementing again. Anyway, FLV format is not directly seekable, so it's not an big issue.
 
> Seems like a lot of complexity. A uint16 could hold any of the frame intervals you listed expressed as nanoseconds: 16,667 to 41,708. But it its what the video people want...

I haven't seen any existing format that uses nanoseconds. A solution based on two integers clearly represents the intent (and the reason of weird framerate values), so engines could act accordingly. Those `1001` values came from analog NTSC-U era and they are still relevant for the current 4K video content.

**Comment by MarkCallow** [comment]
CTTF TSG telecon 5/20/19. Agreed to add this. The metadata will contain the data proposed by @lexaknyazev. The metadata name was not discussed. Propose KTXanimation and it is only valid to have it for 2D texture arrays.

**Comment by MarkCallow** [comment]
I'm working on this and have questions. I need to describe `duration` and `timescale`. From the examples, `duration` appears to be in seconds. Is this true? What is it the "duration" of? Clearly not that of a frame. As for `timescale` it does not appear to be related to any real world measure of time. It seems more like the number of frames in `duration` seconds. So why is it called `timescale`?

> On a side note, bool isLooped should be changed to uint loopCount with 0 meaning unlimited.

How then do indicate the video does not loop? Shouldn't 0 mean no loop and MAX_UINT mean unlimited?

**Comment by lexaknyazev** [comment]
The typical descriptions (from video world) are:
- `duration` - number of "time units" per frame;
- `timescale` - number of "time units" per 1 second.

Thus, the frame duration in seconds is `duration/timescale`.

> How then do indicate the video does not loop?

- `0` - loops infinitely
- `1` - plays once (technically, not a loop)
- `2` - plays twice
- ...

**Comment by MarkCallow** [comment]
Please review PR #103.
