### ISSUE TITLE
Change supercompressionGlobalData offset to UInt32?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#71]
Currently it is 64-bits but the only things preceding the data in the file are the header, the index, the DFD and the key-value data. It is inconceivable that these things would total more than 4GB.

**Comment by lexaknyazev** [comment]
This would break `bytesOfSupercompressionGlobalData` alignment. Do we expect more header changes?

**Comment by MarkCallow** [comment]
I'm thinking about removing typeSize.

**Comment by lexaknyazev** [comment]
I'd agree with both changes.

**Comment by MarkCallow** [comment]
`typeSize` and `supercompressionGlobalDataOffset` are in different sections of the header. Removing the first would break alignment of `bytesOfImageData` and changing the second would break alignment of the following bytesOfSupercompressionGlobalData.
