### ISSUE TITLE
KTXwriter

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#81]
I am having second thoughts about KTXwriter metadata. The problem is that it makes simple diffs less useful. KTX2 files could have identical content except for the KTXwriter value. Since the value includes the writer's version number, files created from the same sources, by the same user using the same tool could fail to compare equal. The user could easily overlook an updated tool version especially if the updates are automatic.

I see the attraction of identifying tools that create malformed files but I don't want to have to  write custom diff tools for KTX2 that would ignore this field.

Comments? Suggestions?

**Comment by lexaknyazev** [comment]
In case of compressed data, simple diffs could be useless as well.

I'm fine with removal of `KTXwriter` metadata as long as we can provide and support a comprehensive conformance suite: a validation tool and a set of KTX2 files that utilize every format feature possible.

We could also say that tools should write this metadata entry only in "debug" mode.

**Comment by MarkCallow** [comment]
CTTF TSG telecon 5/20/19. Proposal is to make this optional. Also suggested that libktx should add its version info after any set by an application using it, separated by a " / ".

**Comment by zeux** [comment]
FWIW I just encountered the fact that KTXwriter was mandatory and this was somewhat unfortunate - without this field I could just omit handling of key-value pairs, but to satisfy the spec requirement I had to implement full support for it. It would be great to make KTXwriter optional, as this will simplify the tools that want to produce .ktx files.

**Comment by MarkCallow** [comment]
I'm actually happy that it made you implement support for key-value pairs because some of them, particularly KTXorientation are useful.

The purpose of KTXwrite is to identify the generating software. If it is optional I'd hazard a guess that writers that omit it are likely to not be rigorous in other respects too.

**Comment by zeux** [comment]
> If it is optional I'd hazard a guess that writers that omit it are likely to not be rigorous in other respects too.

I'm not sure why this follows - other key-value pairs can usually be omitted as well (e.g. you can output KTXorientation but I'd expect that no KTXorientation is treated the same as `rd`).

KTX1 didn't have required key-value pairs, and KTXwriter in particular doesn't seem to serve a purpose for the processing of the files (that is, it's hard to imagine any reader acting on KTXwriter value), so I don't quite see why this is not optional.
