### ISSUE TITLE
Is KTX2 specification finalized yet?

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/KTX-Specification#82]
I've been trying to google this, and its very hard to even find the right hits for KTX.

I can see there was a draft in 2019, is the KTX2 spec out yet?

**Comment by MarkCallow** [comment]
The status is as described in the latest published draft at http://github.khronos.org/KTX-Specification/.

> Ready for trial implementation. Be aware that changes may be made if issues are discovered during trial. In particular changes may be made to the DFD support. KTX2 files to this specification should NOT be distributed.

There may also be additions to the prohibited formats list and changes to the Crunch supercompression support.

We want to have at least 2 implementations before finalizing the spec. These are underway. We welcome other implementions as well.

Please describe the difficulties you had finding this repo. You did eventually land at the right place. This is the home for KTX2 (& KTX). I would like to see if there is something we can do to make searching easier.

**Comment by MarkCallow** [comment]
I'm closing this as the question is answered but please feel free to add information about the problems you had finding the repo.
