### ISSUE TITLE
Change offset and length names to match glTF

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#85]
glTF will mirror part of the KTX2 header in a JSON schema. glTF has a convention to use byteOffset and byteLength as the names of the related items. For consistency and avoidance of confusion it would be good to use the same names within the KTX2 spec. Since these names do not appear in the KTX2 file, changing is not a problem.

So change offset to byteOffset and bytesOfXXX to XXXByteLength.

Also refer to the glTF KTX2 as an example of providing a separate KTX2 header.

**Comment by lexaknyazev** [comment]
For reference, [current JSON-Schema draft](https://github.com/KhronosGroup/glTF/blob/khr_ktx2_ibl/extensions/2.0/Khronos/KHR_image_ktx2/schema/image.KHR_image_ktx2.schema.json).

**Comment by MarkCallow** [comment]
How can you get GitHub to close issues automatically when the PR is merged?

**Comment by lexaknyazev** [comment]
@MarkCallow 
https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by MarkCallow** [comment]
arrayElementCount seems awkward alongside faceCount and levelCount. I'd like to change it to layerCount. What do you think @lexaknyazev?

**Comment by lexaknyazev** [comment]
Sounds good. Vulkan also calls them layers.
