### ISSUE TITLE
How to carry the Basis bitstream?

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Specification#86]
We have to figure out how to indicate the texture data is using Basis supercompression and can be transcoded.  We'll likely have to use VK_FORMAT_UNKNOWN, because inflation and transcoding are done together. If they were done separately post-inflation would be ETC1S. IIUC as it is now you have to tell the transcoder you want ETC1 in order to get the ETC1S output.

The DFD will probably just provide the color model, primaries and transfer function and have no sample info.

So we need something else to identify it as Basis. Is identifying the supercompressionScheme as Basis enough?

**Comment by lexaknyazev** [comment]
Here's how `.basis` files are structured now.

![image](https://user-images.githubusercontent.com/3479527/59369650-eaa41500-8d51-11e9-82c0-1b52d303f8e1.png)

A couple restrictions from the basisu source code:
- Each image consists of one (RGB) or two (RGB + A) slices.
- The alpha data should immediately follow the color data, and have the same resolution.

Most of these fields are somewhat redundant in KTX2, so we can rearrange them based on KTX2 constraints:
- Width and height are given in the KTX2 header and must be a multiple of a block size for compressed formats so we don't need them for each slice.
- The number of mip levels is also present in the KTX2 header.
- The total number of images and the texture type can be derived from KTX2 dimensions and metadata fields.
- KTX2 supports arbitrary image orientation, so `flipY` seems to be covered as well.
- Framerate will be covered by `KTXanimation` metadata.

**Proposed integration**
- Global alpha presence flag, endpoint codebook, and Huffman tables go into `supercompressionGlobalData` KTX2 section.
- KTX2 has a fixed structure looking like: levels / array elements / faces / z_slices / xy_blocks and provides offsets only for mip-levels. Given that each Basis slice can have a different byte length, we need an additional index section for each mip level.
  - Such indices (with I-Frame flags for video) could also be stored in `supercompressionGlobalData` KTX2 section.
- No other headers are needed.

**Comment by MarkCallow** [comment]
@lexaknyazev please create a draft PR following the outline you have proposed. It looks good. I don't have time due to the implementation work. Sorry.

**Comment by MarkCallow** [comment]
@lexaknyazev, will you be able to draft the PR?

**Comment by lexaknyazev** [comment]
Here's the first draft. Just the layout, a proper PR would require some descriptive language.

Assuming that the `supercompressionScheme` is set to the value that means "Basis Universal".

### Supercompression Global Data Layout
```
uint32 globalFlags
uint16 endpointCount
uint16 selectorCount
uint32 endpointsByteLength
uint32 selectorsByteLength
uint32 tablesByteLength

for each layer in layerCount (1 if 0)
  for each face in faceCount (1 or 6)
    for each z_slice in pixelDepth (1 if 0)
      uint32 sliceFlags
      uint32 sliceByteOffset
      uint32 sliceByteLength
      if (globalFlags & alpha)
        uint32 alphaSliceByteOffset
        uint32 alphaSliceByteLength

byte[endpointsByteLength] endpointsData
byte[selectorsByteLength] selectorsData
byte[tablesByteLength] tablesData
```

`sliceByteOffset` and `alphaSliceByteOffset` are relative to the start of the corresponding mip level.

While KTX2 uses uint64 offsets and byte lengths for mip-levels, Basis limits slices to uint32. Should we change that?

### Mip-level Data Layout
```
for each layer in layerCount (1 if 0)
  for each face in faceCount (1 or 6)
    for each z_slice in pixelDepth (1 if 0)
      byte[sliceByteLength] colorSliceData
      if (globalFlags & alpha)
        byte[alphaSliceByteLength] alphaSliceData
```

### Video
Basis Universal supports inter-frame (video) encoding for 2D slices. The most fitting KTX feature for temporal axis seems to be `layerCount` (that would be equal to the number of frames). `sliceFlags` can be used to mark whether a frame is I or P. Extra care would be needed for the decoder to support video sequences on cubemaps or sliced 3D images (i.e., maintain several I/P states simultaneously). KTX2 files with I/P Basis frames must have `KTXanimation` metadata.

**Comment by MarkCallow** [comment]
> While KTX2 uses uint64 offsets and byte lengths for mip-levels, Basis limits slices to uint32. Should we change that?

It seems unlikely that a Basis supercompressed slice will exceed 4GB so I don't see an issue with a 32-bit `sliceByteLength`.  However if there is a very long mipmapped array or deep 3D texture then a 32-bit offset is potentially not enough, especially as we are talking about video.

Is there something fundamental about Basis that limits a level to a 32-bit size?

I think the rest of the proposal is fine. Even cubemaps and sliced 3D images shouldn't be a problem as each face or slice will have a different Basis slice and therefore a unique flag value.

Does .basis says anything about the order of cubemap faces?

**Comment by lexaknyazev** [comment]
> Is there something fundamental about Basis that limits a level to a 32-bit size?

A slice, not the whole level. We should ask Rich about that.

> order of cubemap faces

In its core, Basis doesn't care about layers or faces. It treats all of them as 2D images. When `.basis` file headers indicate that it's a cubemap, the order of faces is the same as in KTX. Although it's an implementation detail for `.basis`->`.ktx2` pipeline, not relevant to embedding.

**Comment by MarkCallow** [comment]
I'm finding it inconvenient to have optional `alphaSliceByte{Offset,Length)` fields in the global data. Because the slice description structures are different it looks like I'm going to end up with 2 loops at writing and 2 at reading, 1 for each type of structure. How about always having these fields but making there values 0 if there is no alpha?

**Comment by MarkCallow** [comment]
Should we include `extendedByteLEngth` and `extendedData` in the global data so we can take advantage of whatever extensions are made to Basis? Or should we use a different `supercompressionScheme` id for future versions of Basis?

**Comment by MarkCallow** [comment]
In order to simplify the code I have added endpoints, selectors and tables byteOffsets within the sgd. I have also decided to add `extendedByteOffset` and `extendedByteLength`. 

Re. the "slice" descriptions, I always include the alphaSlice fields as I was going to have to repeat too much code if there were 2 different versions of the structure. These descriptions need an outer loop over the mip levels too. Here is what I have right now:

```
uint32_t globalFlags
uint16_t endpointCount;
uint16_t selectorCount;
uint32_t endpointsByteOffset;
uint32_t endpointsByteLength;
uint32_t selectorsByteOffset;
uint32_t selectorsByteLength;
uint32_t tablesByteOffset;
uint32_t tablesByteLength;
uint32_t extendedByteOffset;
uint32_t extendedByteLength;

for each level in levelCount (1 if 0)
  for each layer in layerCount (1 if 0)
    for each face in faceCount (1 or 6)
      for each z_slice in pixelDepth (1 if 0)
        uint32 sliceFlags
        uint32 sliceByteOffset
        uint32 sliceByteLength
        uint32 alphaSliceByteOffset
        uint32 alphaSliceByteLength

byte[endpointsByteLength] endpointsData
byte[selectorsByteLength] selectorsData
byte[tablesByteLength] tablesData
byte[extendedByteLength] extendedData
```

`sliceByteOffset` and `alphaSliceByteOffset` are relative to the start of the corresponding mip level. The other offsets are relative to the start of the supercompression global data.

**Comment by MarkCallow** [comment]
We have a problem with `uncompressedByteLength`s when using Basis supercompression. This value is not known until the transcode target format is known. I had originally intended this would be the size in ETC1S format but given that inflation and transcoding are tightly bound the information is not useful. I propose that for the Basis case, these fields should be set to 0 meaning unknown.

In my WIP the transcoding function automatically allocates the necessary memory which, on successful transcoding, will replace the memory holding the Basis data.

**Comment by lexaknyazev** [comment]
>  In order to simplify the code I have added endpoints, selectors and tables byteOffsets within the sgd.

Please keep in mind that such simplification will have its cost - each point of data redundancy makes validation more complex and makes naive implementations more vulnerable to maliciously constructed files.

> I was going to have to repeat too much code if there were 2 different versions of the structure.

I don't quite understand why 2 separate versions of code are needed. Nevertheless, even with the originally proposed structure, the slice information takes too much space: most bytes will be zeros for the most practical use cases. A possible mitigation is to switch uint32 to some kind of varint encoding (e.g., LEB128).

> I propose that for the Basis case, these fields should be set to 0 meaning unknown.

Agree, but with "must" instead of "should".

**Comment by MarkCallow** [comment]
Because of the potentially varying number of images within a level - when mipmapping 3D textures - for random access or loading the smallest level first, I think we need an index of the first image/slice description of a level. It doesn't need to be an offset. It can just be the image number.
Any thoughts?

Once I have everything working, I'll revisit the byte offsets for the endpoints etc.

**Comment by lexaknyazev** [comment]
> we need an index of the first image/slice description of a level
> It can just be the image number.

Sorry, I don't follow. Could you give an example?

**Comment by MarkCallow** [comment]
We have a array of slice descriptions. For random access to a level we need to know the level's first slice in the array. Since the number of images varies by level, with 3D textures, figuring that out requires a loop. I propose an array of first slices, indexed by level so firstSlices[level] gives you the index in the slice array to start transcoding. I am also thinking of adding an imageCount field to the Basis SGD header and removing those offset fields I added. With imageCount it is easy to calculate the offsets and the size of this new index.

BTW, these aren't really slices. We have one entry per-pair of Basis slices (for the alpha case) so I'm looking for a different term.

**Comment by MarkCallow** [comment]
This is what I have now:

```
    uint32_t globalFlags;
    uint16_t endpointCount;
    uint16_t selectorCount;
    uint32_t imageCount;
    uint32_t endpointsByteLength;
    uint32_t selectorsByteLength;
    uint32_t tablesByteLength;
    uint32_t extendedByteLength;

    uint32_t firstImages[levelCount];

    for each image in imageCount
        uint32 sliceFlags
        uint32 sliceByteOffset
        uint32 sliceByteLength
        uint32 alphaSliceByteOffset
        uint32 alphaSliceByteLength

    // Images in the above are laid out in the order of layer, face and z_slice
    // by the following loop
    // for each layer in layerCount (1 if 0)
    //    for each face in faceCount (1 or 6)
    //        for each z_slice in the level's pixelDepth (1 if 0)

    byte[endpointsByteLength] endpointsData
    byte[selectorsByteLength] selectorsData
    byte[tablesByteLength] tablesData
```

The reason for always having the alpha slice information is to allow use of a `sliceDesc` structure in the code. Without it or with a separate `sliceDesc` for non-alpha and alpha cases, I fear the code will become even more messy.

**Comment by lexaknyazev** [comment]
`imageCount` should be omitted from the bitstream and defined as
```
int imageCount = (levelCount > 0 ? levelCount : 1) * (layerCount > 0 ? 1 : layerCount) * faceCount * (pixelDepth > 0 ? pixelDepth : 1);
```
This line has to be present in the code anyway because an implementation needs to check headers for validity.

**Comment by lexaknyazev** [comment]
And `totalPixelDepth` can be derived as:
```c
int totalPixelDepth = max(pixelDepth, 1);
for(int i = 1; i < levelCount; i++) totalPixelDepth += max(pixelDepth >> i, 1);
```

**Comment by lexaknyazev** [comment]
After some consideration, I don't think that storing `firstImages` array in the file is needed. Building it at runtime is straightforward:
```c
// assuming that firstImages[0] is always 0
for (int i = 1; i < max(levelCount, 1); i++)
    firstImages[i] = max(layerCount, 1) * faceCount * max(pixelDepth >> i, 1);
```

Given that for all practical purposes the number of levels is rather small (e.g. 16 for the current maximum image size of 32k), computing those helper values at runtime would have near-zero performance impact.

**Comment by MarkCallow** [comment]
The imageCount calculation is not correct. For example for a 5-level 2D texture the result is 25 because it is multiplying levelCount (5) by totalPixelDepth (also 5).

**Comment by lexaknyazev** [comment]
> Removing `max(levelCount, 1) * ` seems to make it correct.

Yes. Since `totalPixelDepth` already includes all levels.

> The firstImages loop is also wrong.

Yes. If it should contain the indices of the first images of each level, the values should accumulate.

All these fixed snippets could be combined to this:
```c
// firstImages contains the indices of the first images for each level
int[max(1, levelCount)] firstImages;

// Invariant value
int layersFaces = max(layerCount, 1) * faceCount;

int imageCount = max(pixelDepth, 1);

// first index is always 0
for (int i = 1; i < levelCount; i++) {
  imageCount += max(pixelDepth >> i, 1);
  firstImages[i] = firstImages[i - 1] + layersFaces * max(pixelDepth >> (i - 1), 1);
}
imageCount *= layersFaces;
```

Alternatively, the loop can be continued one more time to perform less operations within it:
```c
// firstImages contains the indices of the first images for each level
// the last value contains the total number of images
int[max(1, levelCount) + 1] firstImages;

// Invariant value
int layersFaces = max(layerCount, 1) * faceCount;

// first index is always 0
for (int i = 1; i < max(1, levelCount) + 1; i++) {
  firstImages[i] = firstImages[i - 1] + layersFaces * max(pixelDepth >> (i - 1), 1);
}
int imageCount = firstImages[max(1, levelCount) + 1];
```

Please confirm.

**Comment by MarkCallow** [comment]
Here's the final SGD as used in what I've just pushed to https://github.com/MarkCallow/KTX-Software/tree/basis.

```
    uint32_t globalFlags;
    uint16_t endpointCount;
    uint16_t selectorCount;
    uint32_t endpointsByteLength;
    uint32_t selectorsByteLength;
    uint32_t tablesByteLength;
    uint32_t extendedByteLength;

    for each image in imageCount
        uint32 sliceFlags
        uint32 sliceByteOffset
        uint32 sliceByteLength
        uint32 alphaSliceByteOffset
        uint32 alphaSliceByteLength

    // Images in the above are laid out in the order of layer, face and z_slice
    // by the following loop
    // for each level in levelCount (1 if 0)
    //    for each layer in layerCount (1 if 0)
    //        for each face in faceCount (1 or 6)
    //            for each z_slice in the level's pixelDepth (1 if 0)

    byte[endpointsByteLength] endpointsData
    byte[selectorsByteLength] selectorsData
    byte[tablesByteLength] tablesData
```

**Comment by jherico** [comment]
I'm trying to write a basis aware KTX2 parser and I'm having trouble with the validating the supercompression data in the test file `FlightHelmet_baseColor.ktx2` in commit `855a16449e6bd81b0d68dfa3f61df499201919c1`

The KTX2 header says there are 7217 bytes of sgd data, and implies there is only one image (`pixelDepth` and `arrayElementCount` are 0, `faceCount` and `levelCount` are 1).

Within the basis SGD data as laid out above, the fields between `globalFlags` and `extendedByteLength` take up 24 bytes.  each image takes up 20 bytes and we have only 1.

`endpointsByteLength` is 1007,  `selectorsByteLength` is 4950, `tablesByteLength` is 1212 and `extendedByteLength` is 0.

So....

24 + (1 * 20) + 1007 + 4950 + 1212 + 0 adds up to 7213... 4 bytes less than the 7217 specified in the top level KTX header.  My question is what are those 4 bytes?  

I can't solve it by putting `align(4)` between the different byte arrays as still leaves 1 byte left over at the end, and the data in the hypothetical alignment regions isn't zero'd out.  

On the other hand putting an `align(8)` between the image descriptors and the the `endpointsData` does result in exactly 7217 consumed after I've read the `tablesData` but again, if those are padding bytes, they should be zero'd out and in the file they aren't.  

Is the file or this sgd layout out of date , or am I missing something?

**Comment by MarkCallow** [comment]
Awesome catch! Thanks.

This is due to a piece of code left-over from when I had `uint32_t firstImages[levelCount];`. See the comment from July 10th. We subsequently dropped this but I failed to delete that part of the sgd size calculation. I will fix the code and images.

Other than sgd being an unexpected size, those files are okay and will continue to load.

**Comment by MarkCallow** [comment]
[PR](https://github.com/KhronosGroup/KTX-Software/pull/111) done. Waiting for CI to complete before merge.

**Comment by MarkCallow** [comment]
Btw, I'll really happy that you are writing another KTX2 parser.

**Comment by MarkCallow** [comment]
Please review PR #103.
