### ISSUE TITLE
Key/Value ambiguities (section 3.11)

### ISSUE THREAD

**Issue by sevmeyer** [KhronosGroup/KTX-Specification#94]
There are some edge-case ambiguities for the key/value metadata (section 3.11), which might be worth to clarify.

#### Empty key

As I understand it, a key can be empty (`keyAndValue` begins with `0x00`). Is this a good idea? I don't expect empty keys to break any implementation, but they could be quite confusing.

#### Duplicate keys

Currently, the spec does not say what should happen if a key is included multiple times, possibly with different values. The pragmatic approach is to require that keys must be unique per file. Otherwise, there is a need for precedence and sorting rules.

**Comment by MarkCallow** [comment]
There's a sorting rule already but not a precedence rule. There isn't any need for duplicate keys so I'll forbid them.
