### ISSUE TITLE
Notes about levelCount (section 3.7)

### ISSUE THREAD

**Issue by sevmeyer** [KhronosGroup/KTX-Specification#95]
Some things I noticed:

#### Calculation for max

The current max calculation is missing a final floor(), to avoid fractional indexes
(see [Vulkan](https://www.khronos.org/registry/vulkan/specs/1.1/html/vkspec.html#resources-image-miplevel-sizing)).

#### Ambiguous wording

The current wording is (emphasis mine):

> (levelCount = 1) means that a file contains only the *first* level [...]

However, because the levels are stored in reverse order, this could be confusing, as "first" could either be first of the pyramid (level_0), or first in the file (level_p).
I suggest to always refer to levels by their index.

#### Base level name

In KTX, the base level is always level 0. It therefore seems unnecessary to introduce the name level_base:

> Mip level data is ordered from the level with the smallest size images, \(level_p\) to that with the largest size images, \(level_base\) where \(p = levelCount - 1\) and \(base = 0\).

Simpler alternative:

> Mip level data is ordered from the level with the smallest size images, \(level_p\) to that with the largest size images, \(level_0\) where \(p = levelCount - 1\).

Sections that use level_base: 3.7, 3.9.7, 3.13

**Comment by MarkCallow** [comment]
level_base is the term used in OpenGL and Vulkan specs. I think most people understand the term but I am being pedantic and defining it. I think it is good to use _base_ rather than a number to avoid confusion over the ordering of the data. I'll fix the first 2 issues but not the third.
