### ISSUE TITLE
Key/Value size formula (section 3.11.)

### ISSUE THREAD

**Issue by sevmeyer** [KhronosGroup/KTX-Specification#96]
As I understand it, there are some issues with the current size formula (excuse the formatting):

    sum_(i=0)^(n-1)(ceil(keyAndValueByteLength[i] / 4)) * 4
      + keyAndValueByteLength[n]
      = kvdByteLength

- It is missing the size of the keyAndValueByteLength fields themselves (... + n*4)
- keyAndValueByteLength[n] is out of bounds (sum bound should be n-2?)

However, I wonder if this formula is necessary to begin with. Because `keyAndValueByteLength` is arbitrary, the pairs need to be iterated anyway.

**Comment by MarkCallow** [comment]
Yes, the pairs need to be iterated. The purpose of this formula was to offer a validity check for validators and to indicate there must be no extra bytes after the last pair.

**Comment by MarkCallow** [comment]
Thank for this and your other issue reports.
